const prompt = require("prompt-sync")()
salario = Number(prompt("Digite o salário: "))
tempo = Number(prompt("Digite o tempo(anos): "))
quadrienio = Math.floor(tempo / 4) 
acrescimo = salario * (quadrienio * 0.01)
console.log(`Salário: ${salario}`)
console.log(`Tempo: ${tempo}`)
console.log(`Quadriênio: ${quadrienio}`)
console.log(`Salário Final: ${(salario + acrescimo).toFixed(2)}`) 